In [1]:
import numpy as np
import pandas as pd
from dataset import utils
from importlib import reload
import re
import great_expectations as ge
import matplotlib.pyplot as plt
%matplotlib inline
reload(utils)

In [ ]:
Deductible = {"$0":.17,
            "$575":.04,
            "$1,500":-.7,
            "$2,000":-.14}
oop_max = {""}

In [2]:
fname = "/Users/derekmiller/Desktop/2018/2018Jan_conjoint_Denso/PaaK_ConjData.csv"
df = utils.gen_survey_data_from_file(fname)
df.head()

                 RID  vers  C1  C2  C3   C4
0  R_BFKCTSQci2SglwJ    39   2   1   1  1.0
1  R_3p3Tyx4AH8BN6X7    97   3   3   3  3.0
2  R_0GmdmGJYZJlFjuF    16   2   2   1  2.0
3  R_vYRsWqDGBqYLl7j    41   3   3   2  1.0
4  R_3e4feAni7DbzoBX    62   1   2   1  1.0

In [3]:
fname = "/Users/derekmiller/Desktop/2018/2018Jan17_conjoint_Centene/2019_Ambetter_Product_Design_Survey_GConly.csv"
df = utils.gen_survey_data_from_file(fname,drop_row=[1])
df.head()

                 RID  vers  C1  C2  C3  C4  C5  C6
0  R_cwiomkmvhSQzhF7     2   2   1   1   2   2   3
1  R_3PjENDQqsDGSOnI    36   1   3   3   3   3   2
2  R_3nocRRKKQcpHKI2    43   2   3   2   1   2   1
3  R_2s093Htk7qqrLed    16   1   2   1   1   2   1
4  R_3Lj3pZ3XYd8sT3B    18   2   2   3   3   2   2

In [4]:
fname = "/Users/derekmiller/Desktop/OICremo_MD/OutsideIn_Cremo_MaxDiff.csv"
df = utils.gen_survey_data_from_file(fname,model='maxdiff',drop_row=[1])
df.head()

,RID,vers,MD1_1,MD1_2,MD2_1,MD2_2,MD3_1,MD3_2,MD4_1,MD4_2,...,MD7_1,MD7_2,MD8_1,MD8_2,MD9_1,MD9_2,MD10_1,MD10_2,MD11_1,MD11_2
0,R_2wSmjS52s2fpdyW,49,1,3,4,1,4,1,1,4,...,5,1,3,5,2,1,4,3,4,5
1,R_1lltcKidU1UPU5r,49,3,5,2,4,4,2,4,3,...,3,2,4,5,3,4,3,4,3,2
2,R_qzkNsjkfBqLK3hT,49,1,5,1,2,1,5,5,1,...,1,3,3,5,5,4,2,4,3,5
3,R_21uDYAAWFVMLNEr,27,2,1,3,1,3,4,5,2,...,5,4,2,5,2,1,4,3,1,3
4,R_1F34JXvd7VDXZph,7,1,3,1,5,4,3,2,4,...,2,1,1,5,5,4,5,3,2,4