In [188]:
import numpy as np
import pandas as pd
from dataset import utils
from importlib import reload
import re
import great_expectations as ge
import matplotlib.pyplot as plt
%matplotlib inline
reload(utils)

In [189]:
utils.run_tests()

In [190]:
fname = "/Users/derekmiller/Desktop/2018Jan17_conjoint_Centene/2019_Ambetter_Product_Design_Survey_GConly.csv"
df = pd.read_csv(fname)
df_ = pd.DataFrame()

In [191]:
df = utils.gen_survey_data_from_file(fname)
df.head()

,RID,vers,C1,C2,C3,C4,C5,C6
0,ResponseID,vers,Assume all the following options are associate...,Assume all the following options are associate...,Assume all the following options are associate...,Assume all the following options are associate...,Assume all the following options are associate...,Assume all the following options are associate...
1,R_cwiomkmvhSQzhF7,2,2,1,1,2,2,3
2,R_3PjENDQqsDGSOnI,36,1,3,3,3,3,2
3,R_3nocRRKKQcpHKI2,43,2,3,2,1,2,1
4,R_2s093Htk7qqrLed,16,1,2,1,1,2,1

In [192]:
df = utils.gen_survey_data_from_file("/Users/derekmiller/Desktop/Data/PaaK_ConjData.csv")
df.head()

                 RID  vers  C1  C2  C3   C4
0  R_BFKCTSQci2SglwJ    39   2   1   1  1.0
1  R_3p3Tyx4AH8BN6X7    97   3   3   3  3.0
2  R_0GmdmGJYZJlFjuF    16   2   2   1  2.0
3  R_vYRsWqDGBqYLl7j    41   3   3   2  1.0
4  R_3e4feAni7DbzoBX    62   1   2   1  1.0